# Generated by Django 5.1.5 on 2025-01-31 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('LOCACAO', 'Locação')], max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='api.imovel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
